name: GitHub Container Registry Image Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  docker-image:
    if: ${{ vars.DEPLOY_GHCR == 'true' }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    steps:
      # GitHub Packages requires the entire repository name to be in lowercase
      # although the repository owner has a lowercase username, this prevents some people from running actions after forking
      # Inspiration: https://github.com/open-webui/open-webui/blob/main/.github/workflows/docker-build.yaml
      - name: Set repository and image name to lowercase
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >>${GITHUB_ENV}
          echo "FULL_IMAGE_NAME=ghcr.io/${IMAGE_NAME,,}" >>${GITHUB_ENV}
        env:
          IMAGE_NAME: ${{ github.repository }}

      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Extract SERVER_VERSION from launch.sh
        id: extract-version
        run: |
          SERVER_VERSION=$(grep '^SERVER_VERSION=' launch.sh | cut -d '=' -f2 | tr -d '"')
          echo "SERVER_VERSION=$SERVER_VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GHCR registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image (versioned tag)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.FULL_IMAGE_NAME }}:${{ env.SERVER_VERSION }},${{ env.FULL_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
